const englishText = {
  "Glosari":"Glossary","Mod gelap":"Dark mode","Mod cerah":"Light mode","Cetak":"Print",
  "Perjalanan anda":"Your journey","Situasi graduan":"Graduate landscape","Objektif program":"Programme objectives",
  "Jawatankuasa":"Committees","Tempoh latihan":"Training duration","Orientasi":"Orientation","Waktu fleksi":"Flexi hours",
  "Penilaian kompetensi":"Competency assessment","Pelanjutan latihan":"Training extension","Penamatan latihan":"Training termination",
  "Selepas latihan":"After training","Penilaian kefahaman":"Knowledge assessment",
  "Pengenalan kepada Program":"Introduction to the","Pegawai Perubatan Siswazah":"Pegawai Perubatan Siswazah Programme",
  "Panduan interaktif untuk memahami perjalanan latihan, tanggungjawab, penilaian dan langkah selepas tamat sebagai PPS.":"An interactive guide to understanding your training journey, responsibilities, assessments and the steps after completing PPS.",
  "Mulakan perjalanan":"Start the journey","Sambung bacaan":"Resume learning",
  "Nota pembelajaran bebas · Berdasarkan bahan pembentangan PPS 2026":"Independent learning notes · Based on PPS 2026 presentation materials",
  "Laman ini tidak berafiliasi dengan atau mewakili KKM, Bahagian Perkembangan Perubatan atau MPM. Kandungan diringkaskan daripada slaid kemaskini Mac 2026 untuk pembelajaran dan rujukan semula. Rujuk arahan rasmi terkini apabila melaksanakan dasar.":"This site is not affiliated with or representative of KKM, the Medical Development Division or MPM. Content is summarised from slides updated in March 2026 for learning and revision. Refer to the latest official instructions when applying policy.",
  "tahun latihan":"years of training","bahagian belajar":"learning sections",
  "Kenali program":"Understand the programme","Asas, struktur dan posting":"Foundations, structure and postings",
  "Jalani latihan":"Begin training","Orientasi, tagging dan fleksi":"Orientation, tagging and flexi hours",
  "Buktikan kompetensi":"Demonstrate competency","CME, buku log dan penilaian":"CME, logbook and assessment",
  "Selesaikan perjalanan":"Complete the journey","Perakuan dan pendaftaran":"Certification and registration",
  "01 · Gambaran besar":"01 · The big picture","Situasi graduan perubatan di Malaysia":"Medical graduate landscape in Malaysia",
  "Jumlah graduan berubah dengan ketara sejak 2006, sementara laluan latihan melibatkan institusi dalam dan luar negara yang diiktiraf.":"Graduate numbers have changed considerably since 2006, while the training pathway involves recognised institutions in Malaysia and abroad.",
  "Graduan pada 2025":"Graduates in 2025","Universiti diiktiraf MPM":"Universities recognised by MPM","Universiti dalam negara":"Universities in Malaysia","IPTA + IPTS dalam negara":"Public + private universities in Malaysia",
  "Jumlah graduan perubatan":"Number of medical graduates","Pilih bar":"Select a bar","Puncak dalam data slaid ialah 6,134 graduan pada 2019.":"The slide data peaks at 6,134 graduates in 2019.",
  "Ingat":"Remember","Program PPS ialah jambatan daripada pembelajaran dan peperiksaan kepada amalan yang kompeten dan selamat tanpa penyeliaan.":"The PPS programme is the bridge from study and examinations to competent, safe practice without supervision.",
  "02 · Tujuan":"02 · Purpose","Objektif Program PPS":"PPS Programme objectives",
  "Latihan siswazah memenuhi kehendak undang-undang dan membina keupayaan untuk mengamal sendiri dengan selamat.":"Housemanship fulfils legal requirements and develops the ability to practise independently and safely.",
  "Memenuhi Akta":"Meet legal requirements","Memenuhi keperluan Akta Perubatan 1971 bagi laluan daripada pendaftaran sementara kepada pendaftaran penuh.":"Meet the Medical Act 1971 requirements for progression from provisional to full registration.",
  "Kompeten & selamat":"Competent & safe","Membina pengetahuan dan kemahiran klinikal agar pegawai boleh mengamal sendiri dengan selamat.":"Develop the knowledge and clinical skills needed to practise independently and safely.",
  "Profesional":"Professional","Membentuk sikap yang baik dan tahap profesionalisme yang tinggi.":"Develop good conduct and a high standard of professionalism.",
  "Pelajar Perubatan":"Medical Student","Pembelajaran & peperiksaan":"Learning & examinations","Bekerja sambil belajar di bawah penyeliaan":"Work-based learning under supervision","Pegawai Perubatan":"Medical Officer","Kompeten dan selamat tanpa penyeliaan":"Competent and safe without supervision",
  "Intipati Seksyen 13 Akta Perubatan 1971":"Summary of Section 13, Medical Act 1971","Ini ialah ringkasan pembelajaran, bukan petikan undang-undang lengkap.":"This is a learning summary, not the complete legal text.",
  "03 · Tadbir urus":"03 · Governance","Siapa mengurus dan menilai latihan?":"Who manages and assesses training?","Tanggungjawab bergerak daripada peringkat kebangsaan kepada negeri, hospital dan jabatan.":"Responsibilities flow from national level to the state, hospital and department.",
  "Kebangsaan":"National","Negeri":"State","Hospital":"Hospital","Jabatan":"Department",
  "Jawatankuasa PPS di peringkat JKN":"PPS Committee at JKN level","Jawatankuasa PPS Hospital":"Hospital PPS Committee","Jawatankuasa PPS Jabatan":"Department PPS Committee",
  "04 · Evolusi latihan":"04 · Training evolution","Tempoh latihan siswazah":"Housemanship training duration","Pada 2008, Jemaah Menteri memutuskan tempoh latihan ditingkatkan daripada satu kepada dua tahun.":"In 2008, the Cabinet decided to increase training from one year to two years.",
  "Sebelum 2008":"Before 2008","1 tahun · 3 posting major":"1 year · 3 major postings","Keputusan Jemaah Menteri":"Cabinet decision","Tempoh dipanjangkan untuk meningkatkan kualiti, kompetensi dan pendedahan menyeluruh.":"Training was extended to improve quality, competency and breadth of exposure.","Selepas 2008":"After 2008","2 tahun · 6 posting":"2 years · 6 postings","Lima posting major dan satu posting alternatif.":"Five major postings and one alternative posting.",
  "Penting":"Important","Semak cepat":"Quick check","Apakah kesan terputus latihan melebihi empat bulan berterusan?":"What happens when training is interrupted for more than four consecutive months?","Sambung posting terakhir":"Continue the last posting","Ulang latihan dari awal; posting terdahulu tidak sah":"Restart training; previous postings become invalid","Terus memohon pendaftaran penuh":"Proceed directly to full registration",
  "05 · Laluan klinikal":"05 · Clinical pathway","Posting dalam Program PPS":"Postings in the PPS Programme","Setiap posting mempunyai tempoh minimum empat bulan. Susunan ditentukan oleh Jawatankuasa PPS Hospital.":"Each posting lasts at least four months. The sequence is determined by the Hospital PPS Committee.",
  "5 posting major":"5 major postings","1 posting alternatif":"1 alternative posting","Salah satu seawal posting ke-5:":"One may be taken as early as the fifth posting:","Penggiliran mengikut tahun":"Rotation by year","Tahun pertama":"First year","Tahun kedua":"Second year","Minimum setiap posting":"Minimum for each posting","Pertukaran posting sebelum lulus posting semasa":"Changing posting before passing the current posting",
  "06 · Hari pertama":"06 · First days","Program Orientasi di hospital":"Hospital Orientation Programme","Lima hari bekerja untuk menyesuaikan diri, menguasai asas klinikal dan memahami sistem hospital sebelum tagging.":"Five working days to adapt, learn clinical fundamentals and understand hospital systems before tagging.",
  "Waktu":"Hours","Tempoh":"Duration","Selepas":"After","Hujung minggu":"Weekend","5 hari bekerja":"5 working days","Tamat PTM & lapor diri":"Complete PTM & report for duty","Layak 2 hari cuti":"Eligible for 2 days off",
  "Peraturan":"Rule","PPS tidak dibenarkan menjalani tagging semasa Program Orientasi.":"PPS may not undergo tagging during the Orientation Programme.","Segmen pengurusan":"Management segment","Segmen latihan":"Training segment","Susulan":"Follow-up",
  "07 · Persediaan posting":"07 · Posting preparation","Tagging: kenal cara kerja sebelum fleksi":"Tagging: learn the workflow before flexi hours","Tagging berlaku pada awal setiap posting untuk memastikan PPS selamat dan bersedia memasuki waktu bekerja fleksi.":"Tagging takes place at the start of each posting to ensure PPS are safe and ready for flexi working hours.",
  "Mulakan tagging":"Begin tagging","Minimum dua minggu pada awal setiap posting.":"At least two weeks at the start of each posting.","Dapatkan pendedahan":"Gain exposure","Dinilai":"Be assessed","Penilaian dibuat di hujung tempoh tagging untuk keputusan off-tag.":"Assessment is performed at the end of tagging to determine off-tag status.","Off-tag atau lanjut":"Off-tag or extend",
  "Kriteria off-tag":"Off-tag criteria","Tiada masalah sikap":"No conduct concerns","Selamat melaksanakan prosedur asas jabatan":"Safely performs the department's basic procedures","Jika belum bersedia":"If not yet ready",
  "08 · Waktu bekerja":"08 · Working hours","Sistem waktu bekerja fleksi":"Flexi working-hours system","Sistem berubah daripada on-call yang panjang kepada penyeragaman fleksi pada Januari 2019.":"The system evolved from long on-call hours to standardised flexi hours in January 2019.",
  "On call":"On call","Penyeragaman":"Standardisation","Purata tempoh bertugas seminggu":"Average weekly working hours","Tidak boleh bertugas berterusan melebihi had":"Continuous duty must not exceed this limit","Tiada double duty":"No double duty","Tidak dibenarkan pada hari yang sama":"Not permitted on the same day","Bayaran Khas Elaun Fleksi sebulan":"Monthly Special Flexi Allowance","Hari Kelepasan Mingguan, bukan semestinya hujung minggu":"Weekly rest day, not necessarily on a weekend","Cuti gantian":"Replacement leave",
  "Tiga waktu fleksi standard":"Three standard flexi shifts","Pagi":"Morning","Petang":"Evening","Malam":"Night","Perlu semakan":"Needs review",
  "09 · Pembelajaran berterusan":"09 · Continuing learning","Setiap jabatan wajib melaksanakan CME mengikut topik disiplin, dan PPS perlu diberikan protected time.":"Every department must conduct CME based on discipline-specific topics, and PPS must be given protected time.","Wajib hadir":"Attendance required","PPS perlu menghadiri sesi CME":"PPS must attend CME sessions","1 pembentangan":"1 presentation","Bagi setiap sesi penilaian":"For every assessment session","Fleksibel":"Flexible","Bersemuka, atas talian atau nota":"Face-to-face, online or notes","Alat rujukan":"Reference tool","Cari topik CME mengikut posting":"Search CME topics by posting","Kata kunci":"Keyword","Posting":"Posting","Semua posting":"All postings",
  "10 · Bukti kemajuan":"10 · Evidence of progress","Penilaian kompetensi PPS":"PPS competency assessment","Buku Log Digital PPS melalui MPIS digunakan sepenuhnya untuk PPS baharu bermula Oktober 2025.":"The MPIS Digital PPS Logbook has been fully used for newly appointed PPS since October 2025.","Buku log sementara":"Temporary logbook","Format baharu dipersetujui":"New format approved","Pelaksanaan penuh":"Full implementation","Kehadiran dan pembentangan":"Attendance and presentation","Cara membaca pemberat":"Understanding the weightings","Komponen":"Component","Setiap sesi pelanjutan":"Each extension session","Kriteria lulus posting":"Criteria to pass a posting",
  "11 · Apabila latihan perlu ditambah":"11 · When training must be extended","Pelanjutan tempoh latihan":"Training extension","Dua kategori pelanjutan perlu dibezakan: bukan kompetensi dan masalah kompetensi.":"Two extension categories must be distinguished: non-competency and competency-related.","Bukan kompetensi":"Non-competency","Latihan/urusan belum lengkap":"Incomplete training/administrative matters","Masalah kompetensi":"Competency issue","Markah kurang 60%":"Score below 60%","Aliran ringkas":"Simplified flow","Daripada posting kepada pelanjutan":"From posting to extension","Semak kehadiran":"Check attendance","Semak markah":"Check score","Apakah pencetus pelanjutan atas masalah kompetensi?":"What triggers a competency-related extension?","Markah kurang daripada 60%":"A score below 60%",
  "12 · Risiko serius":"12 · Serious risks","Penamatan latihan siswazah":"Termination of housemanship training","Penamatan boleh timbul daripada aspek perkhidmatan, latihan atau perundangan.":"Termination may arise from service, training or legal grounds.","Perkhidmatan":"Service","Kontrak ditamatkan":"Contract terminated","Latihan":"Training","Tidak kompeten":"Not competent","Perundangan":"Legal","Pendaftaran dibatalkan":"Registration cancelled","Peluang sehingga penilaian akhir":"Opportunities up to the final assessment",
  "13 · Keselamatan mengamal":"13 · Safety to practise","Tujuannya ialah menilai dan memastikan pengamal dengan masalah kesihatan atau kompetensi selamat untuk mengamal.":"Its purpose is to assess and ensure that practitioners with health or competency issues are safe to practise.","Penilaian keselamatan mengamal":"Assessment of safety to practise","Fokus kesihatan mental":"Mental-health focus",
  "14 · Selepas tamat":"14 · After completion","Urusan setelah selesai latihan siswazah":"Matters after completing housemanship","Selesaikan empat urusan utama untuk bergerak daripada latihan kepada amalan sebagai pegawai perubatan.":"Complete four key matters to progress from training to practice as a Medical Officer.","Mohon Sijil Pendaftaran Penuh":"Apply for Full Registration","Mohon Annual Practice Certificate (APC)":"Apply for an Annual Practice Certificate (APC)","Urus penempatan":"Arrange placement","Jalani khidmat wajib":"Complete compulsory service","Rekod CPD":"Record CPD",
  "15 · Penilaian kefahaman":"15 · Knowledge assessment","Semak apa yang anda sudah faham":"Check your understanding","Jawab lima soalan ringkas. Keputusan disimpan pada peranti ini sahaja.":"Answer five short questions. Results are stored only on this device.","Belum selesai":"Not completed","Jawab semua soalan untuk melihat skor.":"Answer all questions to see your score.","Perjalanan selesai":"Journey complete","Sedia memulakan latihan dengan lebih jelas.":"Ready to begin training with greater clarity.","Kembali ke atas":"Back to top","Rujukan pantas":"Quick reference","Glosari PPS":"PPS Glossary","Tutup":"Close"
};

Object.assign(englishText, {
  "20 soalan asal telah dibawa ke halaman ini supaya penilaian boleh dijalankan secara tempatan.":"The 20 original questions have been brought into this page so the assessment can run locally.","Soalan, pilihan jawapan, jawapan betul dan maklum balas dikekalkan daripada borang yang dipautkan dalam slaid asal. Kuiz asal disediakan dalam Bahasa Melayu.":"Questions, answer options, correct answers and feedback are preserved from the form linked in the original slides. The original quiz is in Malay.","Semak jawapan":"Check answers","Tetapkan semula":"Reset","0 / 20 dijawab":"0 / 20 answered","Gunakan keputusan kuiz untuk mengenal pasti bahagian yang perlu disemak semula.":"Use your quiz results to identify sections that need further review.",
  "Uji kefahaman melalui kuiz asal":"Test your understanding with the original quiz","Slaid asal menghubungkan PPS kepada kuiz rasmi luaran “QUIZ Pengenalan Program PPS 2026”.":"The original slides direct PPS to the external “QUIZ Pengenalan Program PPS 2026” assessment.","Kuiz sumber asal":"Original source quiz","Kuiz dibuka melalui Fillout dalam tab baharu. Jawapan dan keputusan dikendalikan oleh borang luaran tersebut.":"The quiz opens through Fillout in a new tab. Answers and results are managed by the external form.","Nota":"Note","Pastikan sambungan internet tersedia. Kandungan dan ketersediaan kuiz tertakluk kepada pemilik borang.":"An internet connection is required. Quiz content and availability are controlled by the form owner.","Buka kuiz asal":"Open original quiz","Perjalanan pembelajaran selesai":"Learning journey complete","Gunakan kuiz asal untuk penilaian kefahaman.":"Use the original quiz for the knowledge assessment.",
  "Cari":"Search","Rujukan pantas untuk PPS sedang bertugas":"Quick reference for PPS on duty","Apa yang anda perlu semak hari ini?":"What do you need to check today?","Lompat terus kepada jawapan yang lazim diperlukan semasa menjalani posting.":"Jump directly to answers commonly needed during a posting.","Cari seluruh panduan":"Search the whole guide",
  "Bagaimana hendak lulus posting?":"How do I pass a posting?","Markah, kehadiran dan komponen penilaian":"Scores, attendance and assessment components","Mengapa latihan boleh dilanjutkan?":"Why might training be extended?","Cuti Latihan, kehadiran dan kompetensi":"Cuti Latihan, attendance and competency","Apakah hak dan had waktu fleksi?":"What are the rights and limits of flexi hours?","Jam bertugas, off day dan cuti gantian":"Working hours, rest days and replacement leave","Apakah topik CME posting saya?":"What are my posting's CME topics?","Cari mengikut posting atau kata kunci":"Search by posting or keyword","Apakah risiko penamatan?":"What are the termination risks?","Perkhidmatan, latihan dan perundangan":"Service, training and legal grounds","Apa perlu dibuat sebelum tamat?":"What must I do before completion?","Pendaftaran penuh, APC, CPD dan penempatan":"Full registration, APC, CPD and placement",
  "markah minimum setiap tempoh penilaian":"minimum score for every assessment period","kuota Cuti Latihan setiap posting":"Cuti Latihan quota per posting","minimum setiap posting":"minimum for each posting","maksimum bertugas berterusan":"maximum continuous duty",
  "Rujukan seluruh panduan":"Whole-guide reference","Cari jawapan dengan cepat":"Find an answer quickly","Taip istilah atau soalan":"Type a term or question","Tutup carian":"Close search",
  "posting":"postings","Trend 2006-2025":"2006-2025 trend","Fasa 1":"Phase 1","Fasa 2":"Phase 2","Fasa 3":"Phase 3","Dasar":"Policy",
  "Individu berdaftar sementara perlu memperoleh pengalaman klinikal yang memuaskan sebelum layak memohon pendaftaran penuh. Teks slaid turut menerangkan tempoh minimum satu tahun dan komponen pembedahan, perubatan serta obstetrik dan ginekologi.":"A provisionally registered person must obtain satisfactory clinical experience before becoming eligible to apply for full registration. The slides also describe a minimum period of one year and components in surgery, medicine, and obstetrics and gynaecology.",
  "Hospital Latihan Siswazah":"Housemanship Training Hospital","Jawatankuasa Kelayakan Perubatan (JKP)":"Medical Qualifying Committee (Jawatankuasa Kelayakan Perubatan, JKP)",
  "Urusetia:":"Secretariat:","Pengerusi:":"Chair:","Ketua Pengarah Kesihatan ·":"Director-General of Health ·","Ahli:":"Members:","12 wakil IPKKM, IPTA/IPTS dan MPM.":"12 representatives from IPKKM, public/private universities and MPM.",
  "Menilai dan meluluskan Hospital Latihan Siswazah.":"Assess and approve Housemanship Training Hospitals.","Membincangkan kelulusan, penamatan, penangguhan dan isu latihan yang tidak selesai di hospital/negeri.":"Discuss approvals, termination, deferment and training issues unresolved at hospital/state level.","Memperakukan latihan bagi permohonan pendaftaran penuh.":"Endorse training for full-registration applications.",
  "Pengarah Kesihatan Negeri ·":"State Health Director ·","semua Pengarah HLS negeri ·":"all Housemanship Training Hospital Directors in the state ·","Timbalan Pengarah Kesihatan Negeri (Perubatan).":"Deputy State Health Director (Medical).","Memantau pelaksanaan latihan dan pematuhan garis panduan.":"Monitor training implementation and compliance with guidelines.","Membuat ulasan permohonan pertukaran PPS.":"Review PPS transfer applications.",
  "Mengurus penempatan, rotasi, buku log, isu prestasi dan perkhidmatan.":"Manage placements, rotations, logbooks, performance and service issues.","Memutuskan perakuan pelanjutan dan mengurus permohonan pendaftaran penuh.":"Decide extension recommendations and manage full-registration applications.","Memantau, membimbing, melatih dan menilai PPS.":"Monitor, guide, train and assess PPS.","Menyediakan laporan penilaian, LNPT, CCP dan CCHT serta mengesahkan prosedur.":"Prepare assessment reports, LNPT, CCP and CCHT, and verify procedures.",
  "Pembedahan/Ortopedik, Perubatan/Pediatrik dan O&G berdasarkan Akta Perubatan 1971.":"Surgery/Orthopaedics, Medicine/Paediatrics and O&G under the Medical Act 1971.","Jika PPS tidak hadir menjalani latihan melebihi":"If PPS are absent from training for more than","4 bulan secara berterusan":"4 consecutive months",", latihan dianggap terputus. Posting yang telah lulus menjadi tidak sah, tertakluk kepada keputusan JKP bagi permohonan mengambil kira posting terdahulu.":", training is considered interrupted. Previously passed postings become invalid, subject to JKP's decision on any application to recognise earlier postings.",
  "Pembedahan":"Surgery","Ortopedik":"Orthopaedics","Pediatrik":"Paediatrics","Perubatan":"Medicine","Obstetrik & Ginekologi":"Obstetrics & Gynaecology","Perubatan Kecemasan":"Emergency Medicine","Anestesiologi":"Anaesthesiology","Psikiatri":"Psychiatry","Kesihatan Primer":"Primary Care",
  "Arahan edaran 25 Julai 2025":"Directive circulated on 25 July 2025","Perubatan Dalaman atau Pediatrik Am":"Internal Medicine or General Paediatrics","Pembedahan Am atau Ortopedik":"General Surgery or Orthopaedics","Posting major yang belum dilalui":"Major posting not completed in the first year","Posting Perubatan Kecemasan":"Emergency Medicine posting","4 bulan":"4 months","Bulan ke-4":"Fourth month","Wad subkepakaran dibenarkan selama 2 minggu":"A subspecialty ward placement is allowed for 2 weeks","Tidak dibenarkan":"Not permitted",
  "8 pagi - 5 petang":"8 am - 5 pm","Pendaftaran dan pengenalan Unit PPS":"Registration and introduction to the PPS Unit","Pengurusan, kewangan dan amanat hospital":"Hospital management, finance and leadership briefing","Saringan kesihatan dan imunisasi":"Health screening and immunisation","Rekod perubatan dan sistem maklumat hospital":"Medical records and hospital information systems","Kesihatan pekerjaan, risiko, keselamatan dan kebakaran":"Occupational health, risk, safety and fire training","Sesi khas hospital":"Hospital-specific sessions","Notifikasi penyakit berjangkit":"Infectious-disease notification","Pengenalan Radiologi dan Patologi":"Introduction to Radiology and Pathology","Kesihatan mental dan Patient Safety":"Mental health and Patient Safety","Dokumentasi klinikal dan kod klasifikasi":"Clinical documentation and classification codes",
  "Kursus Basic Life Support dilaksanakan di luar orientasi dan wajib diadakan dalam empat bulan pertama selepas tamat orientasi bagi setiap lantikan.":"The Basic Life Support course is conducted outside orientation and must be delivered within the first four months after orientation for each appointment.",
  "Kenali cara kerja jabatan. Satu hari penuh kelepasan mingguan diberikan.":"Learn the department's workflow. One full weekly rest day is provided.","Jika gagal, tagging dilanjutkan dua minggu dan dinilai semula.":"If unsuccessful, tagging is extended by two weeks followed by reassessment.","Pelanjutan tagging selama dua minggu, diikuti penilaian semula sebelum tamat pelanjutan.":"A two-week tagging extension, followed by reassessment before the extension ends.",
  "Sebelum 2011":"Before 2011","86-106 jam seminggu":"86-106 hours per week","Fleksi":"Flexi","60 jam seminggu":"60 hours per week","Modifikasi":"Modified system","65-75 jam seminggu":"65-75 hours per week","60-62 jam seminggu":"60-62 hours per week","60-62 jam":"60-62 hours","Maks. 14 jam":"Maximum 14 hours","1 hari penuh":"1 full day","Jika bekerja pada Hari Kelepasan Am; digunakan dalam jabatan semasa":"When working on a public holiday; to be used within the current department","7 pagi - 5 petang":"7 am - 5 pm","7 pagi - 9 malam":"7 am - 9 pm","8 malam - 9 pagi":"8 pm - 9 am",
  "Post-night flexi off diberikan selepas selesai hand-over, ward round, CME dan urusan berkaitan. Posting Perubatan Kecemasan berbeza sedikit.":"Post-night flexi off begins after completing handover, ward round, CME and related duties. Emergency Medicine arrangements differ slightly.","Roster dalam slaid ialah contoh. Sahkan waktu dan aturan roster sebenar dengan jabatan/hospital semasa.":"The roster shown in the slides is an example. Confirm actual hours and roster arrangements with your current department/hospital.",
  "Modul disesuaikan dengan keperluan pandemik.":"The module was adapted to pandemic requirements.","29 Dis 2022":"29 Dec 2022","JKP bersetuju penilaian dilaksanakan sepenuhnya secara digital.":"JKP agreed that assessments should be fully digital.","Okt 2025":"Oct 2025","Buku Log Digital PPS digunakan untuk semua PPS baharu.":"The Digital PPS Logbook is used for all newly appointed PPS.","Performed, assisted dan observed procedures":"Performed, assisted and observed procedures","DOPS, Mini-CEX dan CBD":"DOPS, Mini-CEX and CBD","Sesi 1":"Session 1","Sesi 2":"Session 2","Sesi 1 + Sesi 2 membentuk 100% bagi posting biasa. Setiap sesi pelanjutan dinilai sebagai 100%.":"Session 1 + Session 2 form 100% for a standard posting. Each extension session is assessed as 100%.",
  "Tempoh latihan lengkap, cuti tidak melebihi kuota Cuti Latihan, dan markah sekurang-kurangnya":"Complete training duration, leave within the Cuti Latihan quota, and a score of at least","60% bagi setiap tempoh penilaian":"60% for every assessment period",
  "Tempoh latihan tidak lengkap atau cuti melebihi kuota.":"Incomplete training duration or leave exceeding the quota.","Urusan pentadbiran/perkhidmatan berkaitan latihan.":"Training-related administrative/service matters.","Perlu diselesaikan sebelum keputusan kompetensi.":"Must be resolved before a competency decision.","Kuota Cuti Latihan: 10 hari setiap posting":"Cuti Latihan quota: 10 days per posting","Pelanjutan berlaku apabila markah sesi penilaian kurang 60%.":"An extension occurs when an assessment-session score is below 60%.","Isu seperti near miss, medication error atau sikap dinilai melalui komponen berkaitan, khususnya Global Assessment.":"Issues such as near misses, medication errors or conduct are assessed through the relevant components, particularly Global Assessment.","Kehadiran perlu lengkap sebelum pemarkahan akhir.":"Attendance must be complete before final scoring.","Lengkapkan latihan jika tidak cukup":"Complete training if attendance is insufficient","≥60%: lulus":"≥60%: pass","&lt;60%: pelanjutan kompetensi":"<60%: competency extension","Sesi 3 dan 4: dua bulan. Jika masih gagal selepas sesi 4, BPP dimaklumkan untuk sesi 5 di hospital lain.":"Sessions 3 and 4 last two months. If still unsuccessful after session 4, BPP is notified for session 5 at another hospital.","Pertukaran posting":"Posting transfer",
  "Cuti sakit melebihi 90 hari dalam satu tahun kalendar.":"Sick leave exceeding 90 days in one calendar year.","Tidak hadir tanpa kelulusan melebihi 14 hari.":"Absence without approval exceeding 14 days.","LNPT tahunan kurang 60%.":"Annual LNPT score below 60%.","Salahlaku yang dibuktikan dan diperakukan.":"Misconduct that has been proven and endorsed.","JKP boleh menamatkan latihan setelah PPS diberi pelbagai peluang latihan dan masih gagal kompetensi.":"JKP may terminate training after PPS have been given multiple training opportunities and remain unsuccessful in competency.","Pembatalan Sijil Pendaftaran Sementara oleh MPM boleh menyebabkan kontrak dan latihan tamat.":"Cancellation of the Provisional Registration Certificate by MPM may result in termination of the contract and training.","Aliran kompetensi":"Competency pathway",
  "Selepas posting asal, sesi 3 dan 4 berlangsung dua bulan. Sesi 5 ialah penilaian terakhir selama tiga bulan di hospital lain dan melibatkan temu duga JKP. Jika diberi satu lagi peluang, sesi 6 selama tiga bulan boleh berlangsung di hospital sama atau lain. Kegagalan selepas proses ini boleh membawa kepada tamat latihan dan cadangan tamat perkhidmatan kepada SPA.":"After the original posting, sessions 3 and 4 last two months each. Session 5 is a final three-month assessment at another hospital and includes a JKP interview. If one further opportunity is granted, session 6 may run for three months at the same or another hospital. Failure after this process may lead to termination of training and a recommendation to SPA to terminate service.",
  "Tanggungjawab dinyatakan dalam Seksyen 19 Akta Perubatan 1971 (Pindaan 2012) dan Peraturan 43, Peraturan-Peraturan Perubatan 2017.":"Responsibilities are set out in Section 19 of the Medical Act 1971 (2012 Amendment) and Regulation 43 of the Medical Regulations 2017.","Hospital perlu memaklumkan MPM jika PPS/pengamal mempunyai masalah kesihatan mental, fizikal atau penyakit bawaan darah.":"The hospital must notify MPM if a PPS/practitioner has a mental-health condition, physical-health condition or blood-borne disease.","Panel Kajian Semula Perubatan ialah sub-jawatankuasa yang membantu JK FTP menilai pengamal yang mempunyai masalah kesihatan mental.":"The Medical Review Panel is a subcommittee that assists JK FTP in assessing practitioners with mental-health conditions.",
  "Boleh dimohon setelah tamat posting kelima atau seawal posting keenam melalui MeRITS di laman MPM.":"May be applied for after completing the fifth posting or as early as the sixth posting through MeRITS on the MPM website.","Wajib untuk mengamal secara sah, sah satu tahun dan diperbaharui setiap tahun.":"Required for lawful practice, valid for one year and renewed annually.","Permohonan penempatan pegawai selepas tamat latihan siswazah.":"Apply for officer placement after completing housemanship.","Teruskan laluan perkhidmatan selepas latihan.":"Continue the service pathway after training.","Enam CCP diterima sepanjang enam posting. CCHT ialah purata markah enam CCP dan diberikan selepas tamat latihan sepenuhnya.":"Six CCPs are received across six postings. CCHT is the average of the six CCP scores and is issued after training is fully completed.","20 mata CPD diperlukan bagi kitaran semasa untuk APC tahun berikutnya. PPS mula mengumpul 20 mata pada tahun kedua latihan.":"20 CPD points are required in the current cycle for the following year's APC. PPS begin collecting 20 points in the second year of training.","Rekod penglibatan melalui MyCPD KKM atau platform yang diiktiraf. Kategori termasuk aktiviti pendidikan formal, work-based learning, scholarly activities, self-directed learning dan professional activities.":"Record participation through MyCPD KKM or another recognised platform. Categories include formal educational activities, work-based learning, scholarly activities, self-directed learning and professional activities.","Gunakan halaman ini sebagai orientasi dan rujukan pantas. Bagi keputusan operasi atau dasar, sentiasa rujuk arahan rasmi terkini.":"Use this page for orientation and quick reference. For operational or policy decisions, always refer to the latest official instructions.","Sumber utama: slaid “Pengenalan kepada Program Pegawai Perubatan Siswazah 2026”, kemaskini Mac 2026.":"Primary source: “Introduction to the Pegawai Perubatan Siswazah Programme 2026” slides, updated March 2026."
});

const englishGlossary = {
  PPS:"Pegawai Perubatan Siswazah (house officer).",
  HLS:"Hospital Latihan Siswazah (Housemanship Training Hospital).",
  JKP:"Jawatankuasa Kelayakan Perubatan (Medical Qualifying Committee).",
  CME:"Continuing Medical Education: discipline-based continuing learning during a posting.",
  Tagging:"A minimum two-week period at the start of each posting to learn the department's workflow and prepare for flexi hours.",
  "Off-tag":"A decision confirming that PPS have passed the tagging assessment and may enter flexi working hours.",
  Fleksi:"A scheduled working-hours system averaging 60-62 hours per week under the 2019 standardisation.",
  LNPT:"Laporan Nilaian Prestasi Tahunan (Annual Performance Evaluation Report).",
  CCP:"Certificate of Completion of Posting: the completion certificate and score for each posting.",
  CCHT:"Certificate of Completion of Housemanship Training: the average of six CCPs after completing training.",
  MPIS:"Medical Programme Information System, the platform for the Digital PPS Logbook.",
  MPM:"Majlis Perubatan Malaysia (Malaysian Medical Council).",
  APC:"Annual Practice Certificate.",
  CPD:"Continuing Professional Development."
};

const postingLabels = {"Pembedahan":"Surgery","Ortopedik":"Orthopaedics","Obstetrik & Ginekologi":"Obstetrics & Gynaecology","Perubatan":"Medicine","Pediatrik":"Paediatrics","Anestesiologi":"Anaesthesiology","Perubatan Kecemasan":"Emergency Medicine","Psikiatri":"Psychiatry","Kesihatan Primer":"Primary Care"};

function translateStaticPage(lang) {
  window.ppsOriginalText=window.ppsOriginalText||new WeakMap();
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
  const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node=>{
    const value=node.nodeValue, trimmed=value.trim();
    if(!trimmed) return;
    if(!window.ppsOriginalText.has(node)) window.ppsOriginalText.set(node,trimmed);
    const original=window.ppsOriginalText.get(node);
    const translated=englishText[original];
    const next=lang==="en" && translated ? translated : original;
    node.nodeValue=value.replace(trimmed,next);
  });
  document.documentElement.lang=lang;
  document.body.classList.toggle("english",lang==="en");
  document.getElementById("translation-notice").hidden=lang!=="en";
  document.getElementById("language-toggle").textContent=lang==="en"?"BM":"EN";
  document.getElementById("independent-label").textContent=lang==="en"?"Independent learning notes · Based on PPS 2026 presentation materials":"Nota pembelajaran bebas · Berdasarkan bahan pembentangan PPS 2026";
  document.getElementById("independent-disclaimer").textContent=lang==="en"?"This site is not affiliated with or representative of KKM, the Medical Development Division or MPM. Content is summarised from slides updated in March 2026 for learning and revision. Refer to the latest official instructions when applying policy.":"Laman ini tidak berafiliasi dengan atau mewakili KKM, Bahagian Perkembangan Perubatan atau MPM. Kandungan diringkaskan daripada slaid kemaskini Mac 2026 untuk pembelajaran dan rujukan semula. Rujuk arahan rasmi terkini apabila melaksanakan dasar.";
  document.querySelector(".brand").setAttribute("aria-label",lang==="en"?"Back to top":"Kembali ke mula");
  document.getElementById("theme-toggle").setAttribute("aria-label",lang==="en"?"Switch colour theme":"Tukar mod warna");
  document.getElementById("menu-toggle").setAttribute("aria-label",lang==="en"?"Open navigation":"Buka navigasi");
  document.getElementById("side-nav").setAttribute("aria-label",lang==="en"?"Section navigation":"Navigasi bahagian");
  document.getElementById("glossary-close").setAttribute("aria-label",lang==="en"?"Close glossary":"Tutup glosari");
  document.getElementById("lookup-close").setAttribute("aria-label",lang==="en"?"Close search":"Tutup carian");
  document.getElementById("site-search").placeholder=lang==="en"?"Example: Cuti Latihan, off-tag, 60%, APC":"Contoh: cuti latihan, off-tag, 60%, APC";
}
